FROM python:3.11-slim

# create non root user and group with UID 1000
RUN groupadd -g 1000 appgroup && \
    useradd -u 1000 -g appgroup -s /bin/bash -m appuser

WORKDIR /app
RUN pip install --no-cache-dir -r requirements.fastapi.txt

# non-root user ownership
RUN chown -R appuser:appgroup /app
USER appuser

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]