FROM python:3.11-slim

WORKDIR /app

RUN groupadd -g 1000 appgroup && \
    useradd -u 1000 -g appgroup -s /bin/bash -m appuser

COPY requirements.fastapi.txt .

RUN pip install --no-cache-dir -r requirements.fastapi.txt

COPY requirements.fastapi.txt .

RUN chown -R appuser:appgroup /app
USER appuser

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]