FROM python:3.13-slim

RUN groupadd -g 1000 appgroup && \
    useradd -u 1000 -g appgroup -s /bin/bash -m appuser

WORKDIR /dbt

RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir dbt-core dbt-clickhouse==1.9.3

RUN chown -R appuser:appgroup /dbt

USER appuser