name: nse_pulse

x-networks: &app-networks
  - nse_pulse_network

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: dockerfile.airflow
  env_file: .env
  environment:
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_USER}:${AIRFLOW_PWD}@postgres:5432/${POSTGRES_DB}
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
    AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
  depends_on:
    postgres:
      condition: service_started
  networks: *app-networks

services:
  postgres:
    image: postgres:16
    container_name: postgres
    networks: *app-networks
    environment:
      POSTGRES_USER: ${AIRFLOW_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_PWD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  clickhouse:
    image: clickhouse/clickhouse-server:24.1
    container_name: clickhouse
    networks: *app-networks
    env_file: .env
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PWD}
    ports:
      - "${CLICKHOUSE_HTTP_PORT:-8123}:8123"
      - "9005:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  fastapi:
    build:
      context: .
      dockerfile: dockerfile.fastapi
    container_name: FastAPI
    volumes:
      - ./backend:/app
      - ./utility:/app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      CLICKHOUSE_HOST: ${CLICKHOUSE_HOST:-clickhouse}
      CLICKHOUSE_PORT: ${CLICKHOUSE_HTTP_PORT:-8123}
    networks: *app-networks
    depends_on:
      - clickhouse

  dbt:
    build:
      context: .
      dockerfile: dockerfile.dbt
    container_name: dbt
    user: "1000:1000"
    env_file: .env
    environment:
      - HOME=/dbt
    volumes:
      - ./dbt_project:/dbt
    networks: *app-networks
    depends_on:
      - clickhouse
    #command: sleep infinity

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PWD}
    volumes:
      - minio_data:/data
    networks: *app-networks
    ports:
      - "9000:9000"
      - "9001:9001"

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    command: >
      bash -c " airflow db migrate && airflow users create --username ${AIRFLOW_USER} --password ${AIRFLOW_PWD} --firstname ${AIRFLOW_FIRSTNAME} --lastname ${AIRFLOW_LASTNAME} --role ${AIRFLOW_ROLE} --email ${AIRFLOW_EMAIL} "

  webserver:
    <<: *airflow-common
    container_name: webserver
    command: webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./dbt_project:/opt/airflow/dbt_project
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
      airflow-init:
        condition: service_completed_successfully

  scheduler:
    <<: *airflow-common
    container_name: scheduler
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./dbt_project:/opt/airflow/dbt_project
    depends_on:
      postgres:
        condition: service_started
      airflow-init:
        condition: service_completed_successfully

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    networks: *app-networks
    depends_on:
      - clickhouse
    volumes:
      - metabase_data:/metabase-data

volumes:
  postgres_data:
  minio_data:
  clickhouse_data:
  metabase_data:

networks:
  nse_pulse_network:
    driver: bridge
