nse_pulse_dbt:
  target: dev
  outputs:
    dev:
      type: clickhouse
      driver: http               # Usually 'http' or 'native'
      host: clickhouse           # Replace with your ClickHouse host IP/URL
      port: 8123                 
      user: "{{ env_var('clickhouse_user') }}"
      password: "{{ env_var('clikhouse_pwd') }}"
      schema: default            
      
