nse_pulse_dbt:
  target: dev
  outputs:
    dev:
      type: clickhouse
      driver: http
      host: clickhouse           
      port: 8123                 
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PWD') }}"
      schema: nse_pulse
      staging_schema: nse_pulse